
  


version: '3.7'

services:
    web:
        image: wordpress:php7.2-apache
        environment: 
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            WORDPRESS_DB_PORT: 3306
            WORDPRESS_DB_NAME: ${DATABASE_TABLE_NAME}
        volumes: 
            - ./theme:/var/www/html/wp-content/themes/theme
            - ./plugins:/var/www/html/wp-content/plugins/
        ports:
            - 8080:80

        networks: 
            - app-network

    db:
        image: 'mysql:5.7'
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_DATABASE: wordpress
        networks:
            - app-network
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        volumes:
            - './config/phpmyadmin/logs:/var/log/apache2'
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            
        networks:
            - app-network
        ports:
            - 8081:80
networks:
    app-network:
        driver: bridge
              

  


