version: '3.7'

services:
    web:
        image: wordpress:php7.2-apache
        environment: 
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            WORDPRESS_DB_PORT: 3306
            WORDPRESS_DB_NAME: ${DATABASE_TABLE_NAME}
        volumes: 
            - ./theme:/var/www/html/wp-content/themes/theme
            - ./plugins:/var/www/html/wp-content/plugins/

        networks: 
            - app-network
        restart: always
        depends_on: 
            - db

    db:
        image: mysql:5.7
        volumes: 
            - ./config/database/data:/var/lib/mysql
            - ./config/database/logs:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_DATABASE: wordpress
        networks:
            - app-network
        restart: always
networks:
    app-network:
        driver: bridge
              
